FROM python:3.10-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-ansi --no-root

COPY . .
COPY .env .

# Expose port for FastAPI
EXPOSE 8000

# Run the FastAPI frontend
CMD ["python", "automower_tracker/frontend.py"]